services:
  db:
    image: postgres:17.4
    container_name: solocooking-db
    environment:
      POSTGRES_DB: solocookingtest-db
      POSTGRES_USER: solotest
      POSTGRES_PASSWORD: solotest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solotest"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
