spring:
  mvc:
    servlet:
      path: /api

  datasource:
    url: jdbc:postgresql://localhost:5432/solocookingtest-db
    driver-class-name: org.postgresql.Driver
    username: "solotest"
    password: "solotest"

  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
