spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/solocookingtest-db
    driver-class-name: org.postgresql.Driver
    username: "solotest"
    password: "solotest"

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false

  jpa:
    hibernate:
      ddl-auto: none

  logging:
    level:
      org.flywaydb: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
