name: Publish test report
description: Publish JUnit XML test results as a GitHub check

inputs:
  name:
    description: Test report name
    required: true
  path:
    description: JUnit XML report path
    required: true

runs:
  using: composite
  steps:
    - name: Publish test report
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        reporter: java-junit
        list-suites: failed
        list-tests: failed
        max-annotations: '10'
